In [2]:
#date 30 : 3 : 2023
num = 123 
name = "BRIJESH"
print("Hello {} your score is {}".format(name, num))
print("Hello {one} your score is {two} and again {two} ".format(one = name, two = num))

Hello BRIJESH your score is 123
Hello BRIJESH your score is 123 and again 123 


In [33]:
# name.append(" KUMAR")
# print(name) cannot append to str 
# name[2] = '@' 'str' object does not support item assignment
print(name)
list1 = [1, 3, 4, 8]
list1.append(88)
print(list1)

BRIJESH
[1, 3, 4, 8, 88]


In [22]:
dict = {1: [22, 44, 56, 77], 2: 7, 8:90}
print(dict[1][2])
d = {'k1' : {'k2': "Hello Uncle Namaste Sidhe Kam Ki Baat Par Aate hain!."}}
print(d['k1']['k2'])
print(True, False)
l = [2, 4, 5, 9, 1] # List 
# print(l[2] == 2) assignment not allowed in print function 
t = (1, 2, 5, 2, 8) # tuple
print(t[2])

s = {1, 2, 4, 0, 9, 9, 8, 2, 4}
print(s) # set unique + sorted
s.add(5)
print(s)

56
Hello Uncle Namaste Sidhe Kam Ki Baat Par Aate hain!.
True False
5
{0, 1, 2, 4, 8, 9}
{0, 1, 2, 4, 5, 8, 9}


In [27]:
if False :
    print("Condition is True")
elif True :
    print("True Conditioin failed!")
else :
    print("Condition is not True")

True Conditioin failed!


In [39]:
# for x in range(2, 10) :
#     print(x)
x = list(range(2, 10)) 
a = [num**2 for num in x]
print(a)

[4, 9, 16, 25, 36, 49, 64, 81]


In [45]:
# functions in python
def fun(a, b) :
    """
    THIS IS MULTIPLE LINE BAKCHODI.
    """
    # Docstring is information about the function
    print(a, " ", b)
    
    

fun(b=3, a=9)
# press shift + tab to see the docstring 
fun 

9   3


<function __main__.fun(a, b)>

In [47]:
seq = [3, 5, 8, 4, 0]
def twice(num) :
    return num*2

# map() built in function that executes function on every list element returns address typecast to list
list(map(twice, seq))

[6, 10, 16, 8, 0]

In [50]:
t = lambda num : num*2 
print(t(34))
list(map(lambda num: num*2 , seq))

68


[6, 10, 16, 8, 0]

In [52]:
# filter function filters the element passing condition by function(+lambda)
print(seq)
list(filter(lambda num : num%2 == 0, seq))

[3, 5, 8, 4, 0]


[8, 4, 0]

In [58]:
s = "Chal Bhosdwale Rohit!"
a = list(s.split())
a

['Chal', 'Bhosdwale', 'Rohit!']

In [59]:
'Bhosdwale' in a

True

In [64]:
b = ((1, 2), (3, 4), (5, 6))
for x in b :
    print(x[0], x[1], " : ", x)
print("-----------------------")
for (x, y) in b :
    print(x)

1 2  :  (1, 2)
3 4  :  (3, 4)
5 6  :  (5, 6)
-----------------------
1
3
5


# DATA ANALYSIS

In [65]:
# NUMPY
import numpy as np

In [74]:
l1 = [[1,2,5], [3, 5, 7], [8, 6, 2]]
b = np.array(l1)
print(b)
a = np.arange(0, 11)
print(a)
print("1D zeros : ", np.zeros(3))
print("2D zeros : ", np.zeros((2, 3)))

print("1D ones : ", np.ones(3))
print("2D ones : ", np.ones((2, 3)))

[[1 2 5]
 [3 5 7]
 [8 6 2]]
[ 0  1  2  3  4  5  6  7  8  9 10]
1D zeros :  [0. 0. 0.]
2D zeros :  [[0. 0. 0.]
 [0. 0. 0.]]
1D ones :  [1. 1. 1.]
2D ones :  [[1. 1. 1.]
 [1. 1. 1.]]


In [76]:

# linspace function to generate an array of 10 evenly spaced numbers between 0 and 1. 
# The resulting array contains numbers [0.0, 0.111, 0.222, 0.333, 0.444, 0.555, 0.666, 0.777, 0.888, 1.0]
print(np.linspace(0, 5, 10) )

# np.eye(a) generate unit matrix(with diagonal 1 and rest 0) of dimension : axa
print(np.eye(4))


[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [80]:
# Random numbers generation numpy 
print("1D random no. bw 0:1 dimension 5   : ", np.random.rand(5))
print("-----------------------------------------")
print("2D random no. bw 0:1 dimension 5x5 : ", np.random.rand(5, 5))

1D random no. bw 0:1 dimension 5   :  [0.77515193 0.63247618 0.77558471 0.00762361 0.23885079]
-----------------------------------------
2D random no. bw 0:1 dimension 5x5 :  [[0.63545818 0.37566656 0.93417619 0.40680476 0.72509953]
 [0.57960195 0.75161989 0.3755722  0.4766352  0.64999239]
 [0.17515394 0.36684402 0.40370884 0.55786687 0.03075665]
 [0.47611873 0.08787442 0.55578579 0.30544271 0.44208125]
 [0.64815598 0.40985862 0.45946601 0.98658425 0.85040941]]


In [81]:
# generating the negative random numbers bw -1 and +1
print("1D random no. bw 0:1 dimension 5   : ", np.random.randn(5))
print("-----------------------------------------")
print("2D random no. bw 0:1 dimension 5x5 : ", np.random.randn(5, 5))

1D random no. bw 0:1 dimension 5   :  [ 2.06095284  0.96612223  0.06372012 -1.03846808  1.0275637 ]
-----------------------------------------
2D random no. bw 0:1 dimension 5x5 :  [[-1.44768393 -1.64505478  0.67842669 -0.88826099 -1.06741945]
 [-0.80690619  1.60052081 -2.85947317  0.77846036  0.11575754]
 [ 0.14174029  1.27835889 -0.6959844   1.34263479  0.69639049]
 [ 0.83577554  2.15981003 -1.19320161 -1.02810798  1.4396976 ]
 [-1.69058155 -0.44170073 -1.25127796 -0.75464992 -0.0477808 ]]


In [84]:
print(np.random.randint(1, 100)) #(inclusive, exclusive) integer random number bw range
print(np.random.randint(1, 100, 10)) # list of random numbers of length 10

15
[ 4 57 50 15 83 51 37 84 73 80]


In [85]:
arr = np.arange(25)
print(arr.reshape(5, 5))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [89]:
print("index of max element 1D arr", arr.argmax())
arr = arr.reshape(5, 5) 
print("index of max element 2D arr", arr.argmax())
arr

index of max element 1D arr 24
index of max element 2D arr 24


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [90]:
print(arr.shape) # prints the shape of array (5, 5)
print(arr.dtype) # prints the data type of array element

(5, 5)
int32


# Numpy indexing and Selections

In [1]:
# date 31 : 03 : 2023 Friday
import numpy as np

In [8]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
arrCopy = arr.copy()
arrCopy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
arr1 = arr[:6]
arr1[:] = 89
arr1

array([89, 89, 89, 89, 89, 89])

In [11]:
arrCopy[:6] = 48
arrCopy

array([48, 48, 48, 48, 48, 48,  6,  7,  8,  9, 10])

In [14]:
print(arr)     # original array effected by undeclared copy of array
print(arr1)    # undeclared copy of array
print(arrCopy) # declared copy of array doesnt effect original array it is copied from

[89 89 89 89 89 89  6  7  8  9 10]
[89 89 89 89 89 89]
[48 48 48 48 48 48  6  7  8  9 10]


In [15]:
arr2 = np.array([[1, 3, 5], [4, 6, 90], [8, 33, 56]])
arr2

array([[ 1,  3,  5],
       [ 4,  6, 90],
       [ 8, 33, 56]])

In [16]:
print(arr2[2][1], arr2[2,1]) 

33 33


In [20]:
print(arr2[:2,1:]) # arr2[:2,1:] => arr2[row range, col range]

[[ 3  5]
 [ 6 90]]


In [21]:
arr2[:1]

array([[1, 3, 5]])

In [22]:
arr = np.arange(1, 11) 
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
boolArray = arr > 5
boolArray

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [24]:
arr[boolArray]

array([ 6,  7,  8,  9, 10])

In [25]:
arr[arr>3]

array([ 4,  5,  6,  7,  8,  9, 10])

# Numpy Operations

In [29]:
arr = np.arange(0,11) 
print(arr+arr)
print(arr*arr)
print(arr+100)
print(arr/arr)
print(1/arr)

[ 0  2  4  6  8 10 12 14 16 18 20]
[  0   1   4   9  16  25  36  49  64  81 100]
[100 101 102 103 104 105 106 107 108 109 110]
[nan  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
[       inf 1.         0.5        0.33333333 0.25       0.2
 0.16666667 0.14285714 0.125      0.11111111 0.1       ]


C:\Users\brije\AppData\Local\Temp\ipykernel_16548\373811229.py:5: RuntimeWarning: invalid value encountered in true_divide
  print(arr/arr)
C:\Users\brije\AppData\Local\Temp\ipykernel_16548\373811229.py:6: RuntimeWarning: divide by zero encountered in true_divide
  print(1/arr)


In [30]:
print(arr**2)

[  0   1   4   9  16  25  36  49  64  81 100]


In [33]:
print(np.sqrt(arr))
print("Square Root of 15 : ",np.sqrt(15))

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.         3.16227766]
Square Root of 15 :  3.872983346207417


In [34]:
print(np.exp(arr))

[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03 2.20264658e+04]


# PANDAS

In [4]:
import numpy as np
import pandas as pd

In [2]:
labels = ['a', 'b', 'c', 'd']
my_data = [10, 20, 30, 40] 
arr = np.array(my_data)
d = {'a':10, 'b':20, 'c':30, 'd':40 } 

In [4]:
d

{'a': 10, 'b': 20, 'c': 30, 'd': 40}

In [11]:
print(pd.Series(data = my_data))
print("------------------------------")
print(pd.Series(data = my_data, index = labels))
print("------------------------------")
print(pd.Series(my_data, labels))
print("------------------------------")
print(pd.Series(arr*2, labels))

0    10
1    20
2    30
3    40
dtype: int64
------------------------------
a    10
b    20
c    30
d    40
dtype: int64
------------------------------
a    10
b    20
c    30
d    40
dtype: int64
------------------------------
a    20
b    40
c    60
d    80
dtype: int32


In [12]:
pd.Series(d)

a    10
b    20
c    30
d    40
dtype: int64

In [13]:
pd.Series(data = [sum, print, len])

0      <built-in function sum>
1    <built-in function print>
2      <built-in function len>
dtype: object

In [16]:
ser1 = pd.Series([1, 3, 5, 8], ['USA', 'India', 'Germany', 'Israel']) 
ser2 = pd.Series([21, 5, 61, 86], ['UK', 'India', 'Nepal', 'Israel']) 
print(ser1)
print('-------------------')
print(ser2)
print('-------------------')
ser1+ser2

USA        1
India      3
Germany    5
Israel     8
dtype: int64
-------------------
UK        21
India      5
Nepal     61
Israel    86
dtype: int64
-------------------


Germany     NaN
India       8.0
Israel     94.0
Nepal       NaN
UK          NaN
USA         NaN
dtype: float64

# Pandas Dataframe

In [3]:
from numpy.random import randn 
np.random.seed(101)

In [4]:
df = pd.DataFrame(randn(5, 4), ['A', 'B', 'C', 'D', 'E'], ['W', 'X', 'Y', 'Z'])
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [ ]:
# The only important point we need to understand is that using different seeds will cause NumPy to 
# produce different pseudo-random numbers. The output of a numpy.random function will depend on the 
# seed that you use.

In [14]:
print(df['X'])
print('type : ', type(df['X']))

A    0.196800
B   -0.156598
C   -0.610259
D   -0.479448
E    1.862864
Name: X, dtype: float64
type :  <class 'pandas.core.series.Series'>


In [1]:
df = pd.DataFrame(randn(5, 4), ['A', 'B', 'C', 'D', 'E'], ['W', 'X', 'Y', 'Z'])
df

NameError: name 'pd' is not defined

In [21]:
type(df['W']) 

pandas.core.series.Series

In [22]:
type(df)

pandas.core.frame.DataFrame

In [51]:
# single column 
df['W']

A    0.093628
B   -0.380104
C    0.178009
D    1.130018
E   -0.125381
Name: W, dtype: float64

In [52]:
# for multiple columns 
df[['W', 'Z']]

W         Z
A  0.093628 -1.908009
B -0.380104  1.522562
C  0.178009  1.743477
D  1.130018 -1.063049
E -0.125381 -1.046358

In [5]:
# adding two columns W and Y storing in SWY
df['SWY'] = df['W'] + df['Y']
df

W         X         Y         Z       SWY
A  2.706850  0.628133  0.907969  0.503826  3.614819
B  0.651118 -0.319318 -0.848077  0.605965 -0.196959
C -2.018168  0.740122  0.528813 -0.589001 -1.489355
D  0.188695 -0.758872 -0.933237  0.955057 -0.744542
E  0.190794  1.978757  2.605967  0.683509  2.796762

In [54]:
# dropping a particular column in dataframe 
# df = df.drop('SWY', axis = 1) # Method 1 to inplace changes
df.drop('SWY', axis = 1, inplace = True) # Method 2 to inplace changes in dataframe
# axis = 0 -> index, 1-> column

In [55]:
df

W         X         Y         Z
A  0.093628  1.240813 -1.097693 -1.908009
B -0.380104 -1.666059 -2.736995  1.522562
C  0.178009 -0.626805 -0.391089  1.743477
D  1.130018  0.897796  0.330866 -1.063049
E -0.125381 -0.945588  2.029544 -1.046358

In [56]:
# dropping the row
df.drop('E', inplace = True)

In [57]:
df

W         X         Y         Z
A  0.093628  1.240813 -1.097693 -1.908009
B -0.380104 -1.666059 -2.736995  1.522562
C  0.178009 -0.626805 -0.391089  1.743477
D  1.130018  0.897796  0.330866 -1.063049

In [59]:
df.shape

(4, 4)

In [60]:
# selecting column
df['Y']

A   -1.097693
B   -2.736995
C   -0.391089
D    0.330866
Name: Y, dtype: float64

In [62]:
# selecting row
df.loc['C'] # Method 1

W    0.178009
X   -0.626805
Y   -0.391089
Z    1.743477
Name: C, dtype: float64

In [64]:
df.iloc[2] # Mehod 2 of 0 indexing

W    0.178009
X   -0.626805
Y   -0.391089
Z    1.743477
Name: C, dtype: float64

In [65]:
# finding value of (row, col)
df.loc['B', 'Y']

-2.7369945956467303

In [66]:
# select table of desired rows, desired columns
df.loc[['A', 'D'], ['X', 'Z']]

X         Z
A  1.240813 -1.908009
D  0.897796 -1.063049

In [4]:
# conditional selection in dataframe
booldf = df > 0
booldf

W      X      Y      Z
A   True   True   True   True
B   True  False  False   True
C  False   True   True  False
D   True  False  False   True
E   True   True   True   True

In [5]:
df[booldf]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118       NaN       NaN  0.605965
C       NaN  0.740122  0.528813       NaN
D  0.188695       NaN       NaN  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [8]:
df[df > 0]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118       NaN       NaN  0.605965
C       NaN  0.740122  0.528813       NaN
D  0.188695       NaN       NaN  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [9]:
df['W'] > 0

A     True
B     True
C    False
D     True
E     True
Name: W, dtype: bool

In [10]:
# for entire dataframe with df['W'] > 0
df[df['W'] > 0]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [11]:
# only W column of dataframe
df[df['W'] > 0]['W']

A    2.706850
B    0.651118
D    0.188695
E    0.190794
Name: W, dtype: float64

In [6]:
df[df['W'] > 0][['W', 'Y']]

W         Y
A  2.706850  0.907969
B  0.651118 -0.848077
D  0.188695 -0.933237
E  0.190794  2.605967

In [11]:
mycols = ['W', 'Y']
df[df['W'] > 0][mycols]

W         Y
A  2.706850  0.907969
B  0.651118 -0.848077
D  0.188695 -0.933237
E  0.190794  2.605967

# Dataframe Part 2

In [13]:
df[df['W'] > 0]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [16]:
# data fetching on multiple conditioning 
# df[(df['W'] > 0) and (df['Y'] > 0)]
# error ---> The truth value of a Series is ambiguous
# work for single (True and False) not series 

In [6]:
df[(df['W'] > 0) & (df['Y'] > 1)]

W         X         Y         Z       SWY
E  0.190794  1.978757  2.605967  0.683509  2.796762

In [7]:
df[(df['W'] > 0) | (df['Y'] > 1)]

W         X         Y         Z       SWY
A  2.706850  0.628133  0.907969  0.503826  3.614819
B  0.651118 -0.319318 -0.848077  0.605965 -0.196959
D  0.188695 -0.758872 -0.933237  0.955057 -0.744542
E  0.190794  1.978757  2.605967  0.683509  2.796762

In [8]:
df.reset_index()

index         W         X         Y         Z       SWY
0     A  2.706850  0.628133  0.907969  0.503826  3.614819
1     B  0.651118 -0.319318 -0.848077  0.605965 -0.196959
2     C -2.018168  0.740122  0.528813 -0.589001 -1.489355
3     D  0.188695 -0.758872 -0.933237  0.955057 -0.744542
4     E  0.190794  1.978757  2.605967  0.683509  2.796762

In [9]:
newind = "CA NY WY OR CO".split()
newind

['CA', 'NY', 'WY', 'OR', 'CO']

In [10]:
df['States'] = newind
df

W         X         Y         Z       SWY States
A  2.706850  0.628133  0.907969  0.503826  3.614819     CA
B  0.651118 -0.319318 -0.848077  0.605965 -0.196959     NY
C -2.018168  0.740122  0.528813 -0.589001 -1.489355     WY
D  0.188695 -0.758872 -0.933237  0.955057 -0.744542     OR
E  0.190794  1.978757  2.605967  0.683509  2.796762     CO

In [13]:
df.set_index('States')

W         X         Y         Z       SWY
States                                                  
CA      2.706850  0.628133  0.907969  0.503826  3.614819
NY      0.651118 -0.319318 -0.848077  0.605965 -0.196959
WY     -2.018168  0.740122  0.528813 -0.589001 -1.489355
OR      0.188695 -0.758872 -0.933237  0.955057 -0.744542
CO      0.190794  1.978757  2.605967  0.683509  2.796762

In [14]:
df

W         X         Y         Z       SWY States
A  2.706850  0.628133  0.907969  0.503826  3.614819     CA
B  0.651118 -0.319318 -0.848077  0.605965 -0.196959     NY
C -2.018168  0.740122  0.528813 -0.589001 -1.489355     WY
D  0.188695 -0.758872 -0.933237  0.955057 -0.744542     OR
E  0.190794  1.978757  2.605967  0.683509  2.796762     CO

In [17]:
outside = ['G1', 'G1', 'G1', 'G2', 'G2', 'G2'] 
inside = [1, 2, 3, 1, 2, 3]
hier_index = list(zip(outside, inside))
hier_index = pd.MultiIndex.from_tuples(hier_index)
hier_index

MultiIndex([('G1', 1),
            ('G1', 2),
            ('G1', 3),
            ('G2', 1),
            ('G2', 2),
            ('G2', 3)],
           )

In [18]:
df = pd.DataFrame(randn(6, 2), hier_index, ['A', 'B'])
df

A         B
G1 1  0.302665  1.693723
   2 -1.706086 -1.159119
   3 -0.134841  0.390528
G2 1  0.166905  0.184502
   2  0.807706  0.072960
   3  0.638787  0.329646

In [23]:
df.loc['G1'].loc[1]

A    0.302665
B    1.693723
Name: 1, dtype: float64

In [28]:
df.index.names = ['Group', 'Num']
df

A         B
Group Num                    
G1    1    0.302665  1.693723
      2   -1.706086 -1.159119
      3   -0.134841  0.390528
G2    1    0.166905  0.184502
      2    0.807706  0.072960
      3    0.638787  0.329646

In [29]:
df.loc['G1']

A         B
Num                    
1    0.302665  1.693723
2   -1.706086 -1.159119
3   -0.134841  0.390528

In [31]:
df.xs('G1', level = 'Group')  # everything of G1

A         B
Num                    
1    0.302665  1.693723
2   -1.706086 -1.159119
3   -0.134841  0.390528

In [32]:
df.xs(1, level = 'Num') # indexes by level

A         B
Group                    
G1     0.302665  1.693723
G2     0.166905  0.184502

# PANDAS MISSING DATA

In [35]:
# Missing data --> NAN to be filled by a number or get dropped
import numpy as np
import pandas as pd

In [36]:
d = {'A': [1, 2, np.nan], 'B': [4, np.nan, np.nan], 'C': [7, 9, 5]}
d

{'A': [1, 2, nan], 'B': [4, nan, nan], 'C': [7, 9, 5]}

In [38]:
df = pd.DataFrame(d)
df

A    B  C
0  1.0  4.0  7
1  2.0  NaN  9
2  NaN  NaN  5

In [41]:
df.dropna(axis = 0) # drops all rows with NAN by axis 0 -> row, 1->col

A    B  C
0  1.0  4.0  7

In [42]:
df.dropna(thresh = 2) # the dropping row need to have at least 2 NAN

A    B  C
0  1.0  4.0  7
1  2.0  NaN  9

In [43]:
df.fillna(value = 'undefined')

A          B  C
0        1.0        4.0  7
1        2.0  undefined  9
2  undefined  undefined  5

In [45]:
df['A'].fillna(value = df['A'].mean())

0    1.0
1    2.0
2    1.5
Name: A, dtype: float64

# Groupby

In [46]:
# allow you to group togather rows based off of a column and perform aggregate functions
import numpy as np
import pandas as pd

In [48]:
data = {'Company' : ['GOOG', 'GOOG', 'MSFT', 'MSFT', 'FB', 'FB'],
        'Person' : ['Sam', 'Charlie', 'Vannessa', 'Sarah', 'Amy', 'Carl'],
        'Sales' : [140, 145, 258, 469, 637, 482]}
df = pd.DataFrame(data)
df

Company    Person  Sales
0    GOOG       Sam    140
1    GOOG   Charlie    145
2    MSFT  Vannessa    258
3    MSFT     Sarah    469
4      FB       Amy    637
5      FB      Carl    482

In [50]:
df.groupby('Company').mean()

Person  Sales
Company                 
FB           Carl    637
GOOG          Sam    145
MSFT     Vannessa    469

In [51]:
df.groupby('Company').mean()

Sales
Company       
FB       559.5
GOOG     142.5
MSFT     363.5

In [53]:
df.groupby('Company').sum().loc['GOOG']

Sales    285
Name: GOOG, dtype: int64

In [54]:
df.transpose()

0        1         2      3    4     5
Company  GOOG     GOOG      MSFT   MSFT   FB    FB
Person    Sam  Charlie  Vannessa  Sarah  Amy  Carl
Sales     140      145       258    469  637   482

In [57]:
df.groupby('Company').describe()

Sales                                                        
        count   mean         std    min     25%    50%     75%    max
Company                                                              
FB        2.0  559.5  109.601551  482.0  520.75  559.5  598.25  637.0
GOOG      2.0  142.5    3.535534  140.0  141.25  142.5  143.75  145.0
MSFT      2.0  363.5  149.199531  258.0  310.75  363.5  416.25  469.0

# Merge Join and Concatenate

In [58]:
import pandas as pd

In [65]:
df1 = pd.DataFrame({'A' : ['A0', 'A1', 'A2', 'A3'],
                    'B' : ['B0', 'B1', 'B2', 'B3'],
                    'C' : ['C0', 'C1', 'C2', 'C3'],
                    'D' : ['D0', 'D1', 'D2', 'D3']},
                    index = [0, 1, 2, 3])
df1

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [64]:
df2 = pd.DataFrame({'A' : ['A4', 'A5', 'A6', 'A7'],
                    'B' : ['B4', 'B5', 'B6', 'B7'],
                    'C' : ['C4', 'C5', 'C6', 'C7'],
                    'D' : ['D4', 'D5', 'D6', 'D7']},
                    index = [4, 5, 6, 7])
df2

A   B   C   D
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [66]:
df3 = pd.DataFrame({'A' : ['A8', 'A9', 'A10', 'A11'],
                    'B' : ['B8', 'B9', 'B10', 'B11'],
                    'C' : ['C8', 'C9', 'C10', 'C11'],
                    'D' : ['D8', 'D9', 'D10', 'D11']},
                    index = [8, 9, 10, 11])
df3

A    B    C    D
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [68]:
pd.concat([df1, df2, df3])

A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [69]:
pd.concat([df1, df2, df3], axis = 1)

A    B    C    D    A    B    C    D    A    B    C    D
0    A0   B0   C0   D0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1    A1   B1   C1   D1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2    A2   B2   C2   D2  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3    A3   B3   C3   D3  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4   NaN  NaN  NaN  NaN   A4   B4   C4   D4  NaN  NaN  NaN  NaN
5   NaN  NaN  NaN  NaN   A5   B5   C5   D5  NaN  NaN  NaN  NaN
6   NaN  NaN  NaN  NaN   A6   B6   C6   D6  NaN  NaN  NaN  NaN
7   NaN  NaN  NaN  NaN   A7   B7   C7   D7  NaN  NaN  NaN  NaN
8   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A8   B8   C8   D8
9   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A9   B9   C9   D9
10  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A10  B10  C10  D10
11  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A11  B11  C11  D11

In [ ]:
pd.merge(left, right, how = 'inner', on = 'key')
# left, right --> dataframe, key = col common in left and right sharing some or all same values
# inner --> type of join inner join by default

In [ ]:
pd.merge(left, right, on = ['key1', 'key2'])

In [ ]:
pd.merge(left, right, how = 'outer', on = ['key1', 'key2'])
# how ---> left right inner outer 

In [ ]:
# Joining is a convenient method for combining the column of two potentially differently-indexed 
# dataframe

# Operations

In [ ]:
len(df['col2'].unique())

In [ ]:
df['col2'].value_count() # the number of ways each occur

In [73]:
def times2(x) :
    return (2*x) 

In [75]:
df['Sales'].apply(times2)

0     280
1     290
2     516
3     938
4    1274
5     964
Name: Sales, dtype: int64

In [76]:
df['Sales'].apply(lambda x : x*3)

0     420
1     435
2     774
3    1407
4    1911
5    1446
Name: Sales, dtype: int64

In [77]:
df.columns

Index(['Company', 'Person', 'Sales'], dtype='object')

In [80]:
df.index

RangeIndex(start=0, stop=6, step=1)

In [84]:
df.sort_values(by = 'Sales')

Company    Person  Sales
0    GOOG       Sam    140
1    GOOG   Charlie    145
2    MSFT  Vannessa    258
3    MSFT     Sarah    469
5      FB      Carl    482
4      FB       Amy    637

In [83]:
df.isnull()

Company  Person  Sales
0    False   False  False
1    False   False  False
2    False   False  False
3    False   False  False
4    False   False  False
5    False   False  False

In [1]:
# df.pivot_table()

# Data Input and Output

In [2]:
# CSV Excel HTMl SQL

In [5]:
from numpy.random import randn 
np.random.seed(101)

In [3]:
import pandas as pd

In [4]:
pwd

'C:\\Users\\brije\\Documents\\Python\\Python CrashCourse'

In [8]:
df = pd.DataFrame(randn(3, 4), ['R1', 'R2', 'R3'], ['C1', 'C2', 'C3', 'C4'])
df

C1        C2        C3        C4
R1 -0.134841  0.390528  0.166905  0.184502
R2  0.807706  0.072960  0.638787  0.329646
R3 -0.497104 -0.754070 -0.943406  0.484752

In [6]:
pd.read_csv('example.csv')

In [ ]:
# writting into csv file
pd.to_csv('example.csv') 

In [ ]:
# Reading an Excel file
pd.read_excel('Excel_sample.xlsx', sheetname = 'sheet1')
# each sheet is a dataframe
df.to_excel('Excel_Sample2.xlsx', sheetname = 'newSheet')

In [8]:
# reading html file
data = pd.read_html('https://www.fdic.gov/bank/indivisual/failed/banklist.html')

In [ ]:
type(data)

In [ ]:
data[0].head()

In [2]:
from sqlalchemy import create_engine

In [12]:
engine = create_engine('sqlite:///memory:')

In [17]:
# df.to_sql('my_table', engine)

In [18]:
# sqldf = pd.read_sql('my_table', con = engine)

In [29]:
import pandas as pd
import sqlalchemy
from urllib.parse import quote

In [30]:
engine = sqlalchemy.create_engine('mysql+pymysql://root:%s@localhost:3306/mydatabase' % quote('Brij@shk01'))

In [31]:
df = pd.read_sql_table('employee', engine)

In [32]:
df

name  Age sex   JoinDate                city   salary employeeId
0    Rajesh   22   M 2002-12-11     Rajnagar 225865  41000.0       None
1    Ramesh   24   M 2003-02-15  Gandhinagar 225865  54000.0       None
2    Amrita   25   F 2002-03-03    Prayagraj 215965  44000.0       None
3     Anant   22   M 2000-01-15       Mumbai 225865  84000.0       None
4    Shivam   24   M 2005-02-15    New Delhi 225865  88000.0       None
5  rajneesh   28   M 2004-12-19      Kanpur, 249863  47000.0       None

In [34]:
# selecting columns from database to store in df
df = pd.read_sql_table('employee', engine, columns = ['name', 'JoinDate', 'salary'])
df

name   JoinDate   salary
0    Rajesh 2002-12-11  41000.0
1    Ramesh 2003-02-15  54000.0
2    Amrita 2002-03-03  44000.0
3     Anant 2000-01-15  84000.0
4    Shivam 2005-02-15  88000.0
5  rajneesh 2004-12-19  47000.0

In [35]:
query = '''
select * from cricket
'''
df = pd.read_sql_query(query, engine)
df

cricket_id     name
0           1   Stuart
1           2  Michael
2           3  Johnson
3           4  flaming
4           5   Hayden

In [39]:
df = pd.read_csv("customers.csv")

In [43]:
df

order_id\tproduct_sold\tselling_price
0                  101\tJewellary\t1800
1                     103\tLaptop\t1300
2                  101\tJewellary\t1800
3                     103\tLaptop\t1300

In [44]:
import pandas as pd
df = pd.read_excel('Excel_Sample.xlsx')
df

Unnamed: 0.1  Unnamed: 0   a   b   c   d
0             0           0   0   1   2   3
1             1           1   4   5   6   7
2             2           2   8   9  10  11
3             3           3  12  13  14  15

In [45]:
df.to_excel('Excel_Sample.xlsx',sheet_name='Sheet1')

In [46]:
df = pd.read_excel('Excel_Sample.xlsx', sheet_name='Sheet1')
df

Unnamed: 0.2  Unnamed: 0.1  Unnamed: 0   a   b   c   d
0             0             0           0   0   1   2   3
1             1             1           1   4   5   6   7
2             2             2           2   8   9  10  11
3             3             3           3  12  13  14  15

In [48]:
# df = pd.read_html('http://www.fdic.gov/bank/individual/failed/banklist.html')

In [ ]:
df[0]